// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbxcpkjiwgpkhfcmfmdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpieGNwa2ppd2dwa2hmY21mbWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNjQ2NjYsImV4cCI6MjA3MjY0MDY2Nn0.CE959fFv-VD9KMi4xIvbYjBhVVOzRBYRgo14L1QBDjg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});